Downloaded a Json Parser but didnt get it to work yet, 'undefined reference to pow'. At this rate may just switch to fdoing it in the target language straight away, tried to do it in C because it was familiar and convenient but this is so much hassle already.